### ISSUE TITLE
Add count parameter to pluralize

### ISSUE THREAD

**Issue by brkn** [poppinss/utils#28]
## Description

Pluralize method is defined like this

https://github.com/poppinss/utils/blob/f0a591bd418a7f3853a2725ea5883728814c67d5/src/Helpers/string.ts#L138-L140

But the pluralize func at the pluralize package accepts 2 other parameters

https://github.com/plurals/pluralize/blob/36f03cd2d573fa6d23e12e1529fa4627e2af74b4/pluralize.js#L175

Can we pass the count parameter at the pluralize util? This would make using this at the edge helper much easier.

Pluralizing like doesnt makes much sense

```hbs
{{itemCount > 1 ? pluralize('piece') : `piece`}}
{{itemCount > 1 ? 'pieces' : 'piece'}} {{-- I might as well not use pluralize at this point --}} 
```

This would make the pluralize much more useful

```hbs
{{pluralize('piece', itemCount)}}
```

## Package version

└─┬ @adonisjs/view@6.1.4
  ├─┬ edge-supercharged@3.1.1
  │ └── @poppinss/utils@3.3.1
  └─┬ edge.js@5.3.5
    └── @poppinss/utils@4.0.4

**Comment by thetutlage** [comment]
Ohh yes. Can you create a PR for the same?

**Comment by brkn** [comment]
Should we pass the third parameter too?

```js
  /**
   * Pluralize or singularize a word based on the passed in count.
   *
   * @param  {string}  word      The word to pluralize
   * @param  {number}  count     How many of the word exist
   * @param  {boolean} inclusive Whether to prefix with the number (e.g. 3 ducks)
   * @return {string}
   */
function pluralize (word, count, inclusive) {
    var pluralized = count === 1
      ? pluralize.singular(word) : pluralize.plural(word);

    return (inclusive ? count + ' ' : '') + pluralized;
  }
```

**Comment by thetutlage** [comment]
Yup. Let's accept all the options
