### ISSUE TITLE
Webpack | Nextjs | Import trace for requested module

### ISSUE THREAD

**Issue by ahmedrowaihi** [poppinss/utils#43]
### Package version

6.7.3

### Describe the bug

bug driven from usage of [flydrive-js](https://github.com/flydrive-js) in next.js

details about bug are mentioned here  [flydrive-js](https://github.com/flydrive-js/core/issues/1)

Proof  [code](https://github.com/flydrive-js/core/issues/1#issuecomment-2195936781)

### Reproduction repo

https://github.com/ahmedrowaihi/flydrive-trace-next-app

**Comment by thetutlage** [comment]
Fixed in https://github.com/poppinss/utils/commit/dc09554aa9fa0e29e253f65577efa2003792bf04

**Comment by ahmedrowaihi** [comment]
Thank you

**Comment by andresgutgon** [comment]
Thanks!
